apiVersion: v1
kind: Service
metadata:
  name: replicas-validating-webhook
  namespace: default
spec:
  selector:
    app: replicas-validating-webhook
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
